pagefilter:
  type: FromFilename

table_extraction:
  # - type: Camelot
  #   params:
  #     flavor: stream
  # - type: Camelot
  #   params:
  #     flavor: lattice
  - type: Unstructured
    params:
      hi_res_model_name: "yolox"
  - type: Unstructured
    params:
      hi_res_model_name: "yolox"
      pdf_image_dpi: 300
  - type: Unstructured
    params:
      hi_res_model_name: "yolox"
      pdf_image_dpi: 500
  - type: UnstructuredAPI
    params:
      hi_res_model_name: "yolox"
  - type: LLamaParse

# table_cleaning:
