# Full workflow
# Requires OpenAI API key and only works with table_extraction:Unstructured and r

pagefilter:
  type: FromFilename

table_extraction:
  img:
    - type: Unstructured
      params:
        pdf_image_dpi: 300
        hi_res_model_name: "yolox"

table_cleaning:
  - type: LLM