pagefilter:
  type: RFClassifier
  params: 
    modelfile: random_forest_model_low_false_positive.joblib

table_extraction:
  img:
    - type: Camelot
      params:
        flavor: stream
    - type: Camelot
      params:
        flavor: lattice
    - type: Unstructured
      params:
        pdf_image_dpi: 300
        hi_res_model_name: "yolox"
